GameType: RANDOM

RoundTimeInSeconds: 60

MaxBlocksInArena: 10

SpawnPointMustBeInArena: true

CanLeaveArena: true

TargetOne:
  Enabled: true
  Material: GREEN_WOOL
  Data: 0
  Points: 1

TargetTwo:
  Enabled: false
  Material: BLUE_WOOL
  Data: 0
  Points: 2
  
TargetThree:
  Enabled: true
  Material: RED_WOOL
  Data: 0
  Points: 5

CanWalkWhenInGame: false
CanTeleportWhenInGame: false

ShootingItem:
  Material: BOW
  Name: '&6Shooting Gallery Gun'
  Lores:
  - '&6Use this bow to shoot the wool!'
  
BulletItem:
  Material: ARROW
  Name: '&6Shooting Gallery Bullet'
  Lores:
  - '&6Use this bullet with your bow!'