main: me.x1machinemaker1x.shootinggallery.Main
name: ShootingGallery
version: 0.6
author: [X1machinemaker1X, SBDeveloper]
depend: [Vault]
description: Shooting Practice!

commands:
  shootinggallery:
    default: op
    aliases: [sg, shootingg, sgallery]
    
permissions:
  shootinggallery.create:
    default: op
  shootinggallery.enable:
    default: op
  shootinggallery.forcestop:
    default: op
  shootinggallery.highscore:
    default: true
  shootinggallery.leave:
    default: true
  shootinggallery.reload:
    default: op
  shootinggallery.remove:
    default: op
  shootinggallery.setspawn:
    default: op
  shootinggallery.use:
    default: true 