main: me.x1machinemaker1x.shootinggallery.Main
name: ShootingGallery
version: 0.2
author: [X1machinemaker1X, SBDeveloper]
depend: [WorldEdit, Vault]
description: Shooting Practice!

commands:
  shootinggallery:
    default: op
    aliases: [sg, shootingg, sgallery]