main: me.x1machinemaker1x.shootinggallery.Main
name: ShootingArcade
version: 0.6
author: [X1machinemaker1X, SBDeveloper]
description: Shooting Practice!

commands:
  shootingarcade:
    default: op
    aliases: [sa]
    
permissions:
  shootingarcade.create:
    default: op
  shootingarcade.enable:
    default: op
  shootingarcade.forcestop:
    default: op
  shootingarcade.highscore:
    default: true
  shootingarcade.leave:
    default: true
  shootingarcade.reload:
    default: op
  shootingarcade.remove:
    default: op
  shootingarcade.setspawn:
    default: op
  shootingarcade.use:
    default: true